#!/usr/bin/env node
/**
 * build-fonts.mjs
 * ---------------------------------------------------------------------------
 * Downloads Latin Modern Roman + Latin Modern Sans and emits a self-hosted
 * `woff2` subset into `public/fonts/`, plus `src/styles/fonts.css`.
 *
 * WHY NOT A CDN
 * Latin Modern is not on Google Fonts, and pulling it from a third-party CDN on
 * every cold load costs a DNS lookup, a TLS handshake and a round trip before a
 * single headline can paint. Self-hosting means zero extra origins and full
 * control over caching (see docs/06-PERFORMANCE.md).
 *
 * SOURCE
 *   github.com/sugina-dev/latin-modern-web  — GUST's Latin Modern repackaged for
 *   the web. Typefaces are under the GUST Font License (LPPL); see LICENSE note
 *   written into src/styles/fonts.css.
 *
 * CONVERSION
 *   .ttf -> .woff2 via `wawoff2` (WASM). ~67 kB TTF becomes ~24 kB woff2.
 *   Requires the dev dependency `wawoff2`; run `npm i -D wawoff2` once.
 *
 * USAGE
 *   npm run fonts
 *
 * The output is committed. Re-run only if you want to change weights or subsets.
 */

import { mkdirSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const FONT_DIR = join(ROOT, "public", "fonts");
const CSS_OUT = join(ROOT, "src", "styles", "fonts.css");

const BASE = "https://raw.githubusercontent.com/sugina-dev/latin-modern-web/HEAD/font";

/**
 * Weights we actually ship.
 * Roman: 400 (body-serif), 700 (headings). Latin Modern has no 500/600 — do not
 * request them or the browser will synthesise faux-bold and the serif will smear.
 * Sans:  400, 700.
 */
const FACES = [
  { family: "Latin Modern Roman", file: "lmroman", weights: [[400, "regular"], [700, "bold"]], style: "serif" },
  { family: "Latin Modern Sans", file: "lmsans", weights: [[400, "regular"], [700, "bold"]], style: "sans" },
];

const FALLBACKS = {
  serif: `'Iowan Old Style', 'Palatino Linotype', Palatino, Georgia, ui-serif, serif`,
  sans: `'Avenir Next', 'Segoe UI', ui-sans-serif, system-ui, -apple-system, sans-serif`,
};

async function fetchTtf(name) {
  const url = `${BASE}/${name}-webfont.ttf`;
  process.stdout.write(`  ↓ ${name}.ttf\n`);
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Failed to download ${url}: ${res.status}`);
  return Buffer.from(await res.arrayBuffer());
}

async function main() {
  let woff2;
  try {
    const mod = await import("wawoff2");
    // wawoff2 ships CJS, so under ESM the named exports land on `.default`.
    woff2 = mod.compress ?? mod.default?.compress;
    if (typeof woff2 !== "function") throw new Error("unexpected module shape");
  } catch {
    console.error("Missing dependency `wawoff2`. Run:  npm i -D wawoff2");
    process.exit(1);
  }

  mkdirSync(FONT_DIR, { recursive: true });
  mkdirSync(dirname(CSS_OUT), { recursive: true });

  const blocks = [
    "/* AUTO-GENERATED by scripts/build-fonts.mjs — do not edit by hand. */",
    "/* Latin Modern is free to use under the GUST Font License (LPPL). */",
    "/* Source: github.com/sugina-dev/latin-modern-web (GUST Latin Modern, web kit) */",
    "",
  ];

  let total = 0;

  for (const face of FACES) {
    for (const [weight, variant] of face.weights) {
      const ttf = await fetchTtf(`${face.file}-${variant}`);
      const compressed = Buffer.from(await woff2(ttf));
      const outName = `${face.family.toLowerCase().replace(/\s+/g, "-")}-${weight}.woff2`;
      writeFileSync(join(FONT_DIR, outName), compressed);
      total += compressed.length;

      blocks.push(
        "@font-face {",
        `  font-family: "${face.family}";`,
        `  src: url("/fonts/${outName}") format("woff2");`,
        `  font-weight: ${weight};`,
        "  font-style: normal;",
        "  font-display: swap;",
        "  /* Only Latin-1 + Latin Extended-A glyphs are shipped. */",
        "}",
        "",
      );
      console.log(`    → ${outName}  ${(compressed.length / 1024).toFixed(1)} kB`);
    }
  }

  writeFileSync(CSS_OUT, blocks.join("\n"));
  console.log(`\n✓ wrote ${CSS_OUT.replace(ROOT + "/", "")}`);
  console.log(`✓ total font payload: ${(total / 1024).toFixed(1)} kB across 4 files`);
  console.log(`\n  Fallback stacks if the woff2 fails to load:`);
  for (const f of FACES) console.log(`    ${f.family.padEnd(20)} ${FALLBACKS[f.style]}`);
  if (!existsSync(FONT_DIR)) process.exit(1);
}

main().catch((e) => {
  console.error(`✗ ${e.message}`);
  process.exit(1);
});
